name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu

    steps:
      - uses: actions/checkout@v2

      # Build any WASM packages we have to build
      # - name: Install wasm-pack
      #   uses: jetli/wasm-pack-action@v0.3.0
      #   with:
      #     version: 'latest'
      # - name: Build the game-of-life package
      #   working-directory: src/pkg/game-of-life/rust
      #   run: wasm-pack build --release --out-name index --target bundler .

      # Build the nodejs and deploy it
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - run: npm ci

      - name: Install lightpanda headless browser (and other requirements)
        run: |
          apt update -y
          apt install -y curl jq coreutils git
          LIGHTPANDA_DIR=`pwd` curl -fsSL https://pkg.lightpanda.io/install.sh | bash

      - name: Build and deploy the site
        run: bash deploy.sh
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
